apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyrent-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easyrent-test
  template:
    metadata:
      labels:
        app: easyrent-test
    spec:
      containers:
        - name: easyrent-test
          image: gcr.io/constellation-275522/easyrent
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets-test
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "easy-rent-test-redis.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 4567
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: easyrent-service-dev
spec:
  selector:
    app: easyrent-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4567

---
apiVersion: v1
kind: Service
metadata:
  name: easyrent-test-nodeport
spec:
  selector:
    app: easyrent-test
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: easyrent-test-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: easyrent-test
    networking.gke.io/managed-certificates: easyrent-test-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: easyrent-test-nodeport
    servicePort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: easyrent-test-certificate
spec:
  domains:
    - easyrent-api-test.cit362.com
